import type { TikTokSoundStats } from "./tiktokSound";
import { createBrowserSession, type BrowserSession, type LaunchedBrowser } from "./tiktokBrowser";

/**
 * Read a TikTok sound's use-count from inside a serverless function.
 *
 * Why this exists next to lib/platforms/tiktokSound.ts, which only needs a
 * fetch: TikTok stopped server-rendering music pages. The count arrives from
 * /api/music/detail/, which answers 200 with an empty body unless the request
 * carries X-Bogus, X-Gnarly, X-Dynosaur and msToken -- generated by TikTok's own
 * client script and not forgeable server-side. A browser produces them as a side
 * effect of loading the page.
 *
 * That is why the nightly `sync-trackers` cron has produced nothing: it calls
 * the fetch path, which for a music page can only ever return null. Ten daily
 * runs, zero snapshots. Not misconfigured -- structurally incapable.
 *
 * The same reasoning previously pushed the reader onto a rented box, which is
 * still the right answer if TikTok starts refusing datacenter ranges. This is
 * the cheaper thing to try first, since a browser is the requirement and Vercel
 * can run one.
 *
 * The parsing below is deliberately identical to
 * scripts/dev/tiktokSoundViaBrowser.mjs. Two copies of arithmetic is what put a
 * percentage into videosAdded24h once already, so if this diverges from that
 * file, that is a bug in itself.
 */

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

/** How long to wait for the page to make its own API call once loaded. */
const PAYLOAD_WAIT_MS = 25_000;



export type SoundBrowserSession = BrowserSession<string, TikTokSoundStats>;

/**
 * One browser for a whole sweep.
 *
 * Launching per sound pays the launch -- about half of each read -- once per
 * sound, and the creator sweep proved the sharper failure: two launches close
 * together race on the binary @sparticuz/chromium extracts to /tmp and die
 * with ETXTBSY. Launch is lazy so a sweep where every sound is skipped, or
 * where the plain fetch answers first, never starts a browser at all.
 */
export function openSoundBrowserSession(): SoundBrowserSession {
  return createBrowserSession(readWith);
}

/** One-shot form for callers reading a single sound. */
export async function fetchSoundStatsViaBrowser(
  tiktokSoundId: string,
  opts: { timeoutMs?: number } = {}
): Promise<TikTokSoundStats | null> {
  const session = openSoundBrowserSession();
  try {
    return await session.read(tiktokSoundId, opts);
  } finally {
    await session.close();
  }
}

async function readWith(
  browser: LaunchedBrowser,
  tiktokSoundId: string,
  timeoutMs: number
): Promise<TikTokSoundStats | null> {
  let page: any = null;
  try {
    page = await browser.newPage({ userAgent: UA, viewport: { width: 1400, height: 1000 } });

    // Take the JSON the page fetches for itself rather than scraping the DOM:
    // same numbers, plus title, artist and cover, and no dependence on how
    // TikTok happens to word "46 videos" this month.
    let payload: any = null;
    page.on("response", async (res: any) => {
      if (payload || !res.url().includes("/api/music/detail/")) return;
      try {
        const body = await res.text();
        if (body) payload = JSON.parse(body);
      } catch {
        /* a truncated or non-JSON body is just not the answer; keep waiting */
      }
    });

    await page.goto(`https://www.tiktok.com/music/x-${encodeURIComponent(tiktokSoundId)}`, {
      waitUntil: "domcontentloaded",
      timeout: timeoutMs,
    });

    const deadline = Date.now() + PAYLOAD_WAIT_MS;
    while (!payload && Date.now() < deadline) await page.waitForTimeout(500);
    if (!payload) return null;

    const info = payload.musicInfo ?? payload.music_info;
    const music = info?.music ?? info;
    const uses = info?.stats?.videoCount ?? music?.videoCount;
    if (typeof uses !== "number" || !Number.isFinite(uses)) return null;

    return {
      usesCount: uses,
      title: typeof music?.title === "string" && music.title ? music.title : null,
      artist: typeof music?.authorName === "string" && music.authorName ? music.authorName : null,
      coverImageUrl: music?.coverLarge ?? music?.coverMedium ?? music?.coverThumb ?? null,
    };
  } finally {
    /* Only the page. The browser belongs to the session, and closing it here
       would end a sweep after its first sound. */
    await page?.close().catch(() => {});
  }
}
