import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { recordSoundSnapshot } from "@/lib/sounds/snapshot";
import { createLogger } from "@/lib/observability/logger";

/**
 * The audio tracker's way in, for a reader that is not this server.
 *
 * A TikTok music page cannot be read by a fetch: the count arrives from
 * /api/music/detail/, which answers empty unless the request carries X-Bogus,
 * X-Gnarly, X-Dynosaur and msToken -- generated by TikTok's own client script,
 * and not forgeable server-side. A real browser produces them by loading the
 * page. That browser also has to sit outside India, where tiktok.com serves a
 * placeholder and the app never boots.
 *
 * So the reading happens on a box that has both, and lands here.
 *
 * What this deliberately is NOT: a second copy of the snapshot arithmetic. The
 * delta, the velocity and the metadata backfill all run through
 * recordSoundSnapshot, the same function the cron and the Refresh button use.
 * That function's own comment records what happened the last time this logic was
 * duplicated -- a percentage ended up in videosAdded24h and a sound with 46 uses
 * reported "+100 videos added". The worker's job is to read a number and hand it
 * over; every decision about what that number means stays here.
 *
 * It is also why the worker never gets DATABASE_URL. A box rented to run a
 * browser against a hostile page is the last place to keep credentials to the
 * database production runs on; it holds one token that can write sound
 * readings, and nothing else.
 */

/**
 * How recently a sound must have been read for losing it to count as an outage
 * rather than a stale row. Generous on purpose: the worker's timer is four
 * hourly, so anything actually being tracked is far inside this, and a genuine
 * outage still alerts for a month before going quiet.
 */
const LIVE_WINDOW_MS = 30 * 24 * 60 * 60 * 1000;

const ReadingSchema = z.object({
  tiktokSoundId: z.string().min(1),
  usesCount: z.number().int().nonnegative(),
  title: z.string().nullish(),
  artist: z.string().nullish(),
  coverImageUrl: z.string().nullish(),
});

const BodySchema = z.object({
  readings: z.array(ReadingSchema).min(1).max(200),
  dryRun: z.boolean().optional(),
});

/**
 * SOUND_INGEST_TOKEN if it exists, CRON_SECRET otherwise.
 *
 * The fallback means this works the moment it deploys, with a secret production
 * already has. The override means the worker can be cut down to a token that
 * only writes sound readings, without a code change, the day that box is worth
 * trusting less than the cron scheduler is.
 */
function isAuthorised(request: NextRequest): boolean {
  const expected = process.env.SOUND_INGEST_TOKEN ?? process.env.CRON_SECRET;
  if (!expected) return false;
  return request.headers.get("authorization") === `Bearer ${expected}`;
}

/**
 * GET — which sounds to read.
 *
 * The worker asks rather than being told, so adding a sound in the app is
 * enough to get it tracked; nothing on the remote box needs editing. Only the
 * id and the TikTok id go over the wire, which is all a reader needs.
 */
export async function GET(request: NextRequest) {
  if (!isAuthorised(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const sounds = await db.tikTokSound.findMany({
    // The worker reads TikTok music pages; an Instagram row is not something it
    // can answer, and handing it one only produces a permanent failure.
    where: { platform: "TIKTOK" },
    select: {
      id: true,
      tiktokSoundId: true,
      title: true,
      snapshots: { orderBy: { recordedAt: "desc" }, take: 1, select: { recordedAt: true } },
    },
    orderBy: { createdAt: "asc" },
  });

  const liveSince = Date.now() - LIVE_WINDOW_MS;

  return NextResponse.json({
    sounds: sounds.map((s) => {
      const last = s.snapshots[0]?.recordedAt;
      return {
        id: s.id,
        tiktokSoundId: s.tiktokSoundId,
        title: s.title,
        /* Was this sound reading until recently?
           It is the difference between an outage and a dead row, and only this
           side knows it. "Has it ever read" is the tempting test and it is the
           wrong one: this database carries three seeded sounds whose TikTok ids
           were invented, and the seeder wrote them seven snapshots apiece, all
           frozen in March. By that test they have read, so a worker would call
           them regressions and exit non-zero on every run forever -- which is
           the same as having no alert at all.
           A sound read within the window is one the tracker was genuinely
           keeping up with, so losing it is worth saying loudly. Anything older
           is reported quietly as a row to look at, not an outage to chase. */
        readRecently: last !== undefined && last.getTime() >= liveSince,
        lastReadAt: last?.toISOString() ?? null,
      };
    }),
  });
}

export async function POST(request: NextRequest) {
  const log = createLogger({ context: { route: "trackers/sounds/ingest" } });
  if (!isAuthorised(request)) {
    log.warn("auth failed", { reason: "bad-or-missing-token" });
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Body must be JSON." }, { status: 400 });
  }

  const parsed = BodySchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Unexpected body.", detail: parsed.error.issues.slice(0, 4) },
      { status: 400 }
    );
  }
  const { readings, dryRun = false } = parsed.data;

  /* Every tracker row for these ids, across every org, and the reading is
     written to ALL of them.

     A tiktokSoundId is TikTok's, not ours: two agencies promoting the same
     release track the same sound, and each owns a separate TikTokSound row.
     Keyed by id alone, the Map kept whichever row Prisma returned last and the
     other org's tracker silently stopped receiving readings — it stayed at
     "awaiting first reading" while a perfectly good count was being written one
     row away. Keyed by platform + id, because the same numeric id can exist on
     both platforms and merging them would point one platform's tracker at the
     other's curve; the worker reads TikTok music pages, so that is the platform
     these readings describe. */
  const sounds = await db.tikTokSound.findMany({
    where: { platform: "TIKTOK", tiktokSoundId: { in: readings.map((r) => r.tiktokSoundId) } },
    select: {
      id: true,
      tiktokSoundId: true,
      title: true,
      artist: true,
      coverImageUrl: true,
      snapshots: { orderBy: { recordedAt: "desc" }, take: 1, select: { usesCount: true } },
    },
  });
  const byTikTokId = new Map<string, typeof sounds>();
  for (const sound of sounds) {
    const bucket = byTikTokId.get(sound.tiktokSoundId);
    if (bucket) bucket.push(sound);
    else byTikTokId.set(sound.tiktokSoundId, [sound]);
  }

  let recorded = 0;
  let unknown = 0;
  let skipped = 0;

  for (const reading of readings) {
    const tracked = byTikTokId.get(reading.tiktokSoundId);
    if (!tracked || tracked.length === 0) {
      // A sound removed from the app between the worker's GET and its POST. Not
      // an error on either side, and inventing a row for it would resurrect it.
      unknown += 1;
      continue;
    }
    // Zero is what an unreadable page looks like once it has been through a
    // parser, and writing it would draw a cliff on the campaign's audio chart.
    if (reading.usesCount <= 0) {
      skipped += 1;
      continue;
    }
    if (dryRun) {
      recorded += tracked.length;
      continue;
    }
    // One reading, one snapshot per tracker row: each org's delta is computed
    // against its OWN previous reading, which is what recordSoundSnapshot does.
    for (const sound of tracked) {
      await recordSoundSnapshot(sound, reading);
      recorded += 1;
    }
  }

  log.info("sound readings ingested", { recorded, unknown, skipped, dryRun });
  return NextResponse.json({ recorded, unknown, skipped, dryRun });
}
