/**
 * Read a TikTok sound's use-count by rendering its page.
 *
 * Why a browser is needed, when lib/platforms/tiktokSound.ts only needs a fetch:
 * TikTok stopped server-rendering music pages. The HTML that comes back is a
 * shell -- no `webapp.music-detail` in the rehydration payload, no JSON-LD, not
 * even a meta description -- and the count arrives later from
 * `/api/music/detail/`. That endpoint answers 200 with an empty body unless the
 * request carries `X-Bogus`, `X-Gnarly`, `X-Dynosaur` and `msToken`, which are
 * generated by TikTok's own client script. A browser produces them as a side
 * effect of loading the page; a server cannot forge them.
 *
 * So this lives in scripts/, not in lib/. The nightly cron still uses the fetch
 * path and will report a failure for music pages rather than inventing a number,
 * which is the honest outcome until there is a real API for it.
 */
import { chromium } from "playwright";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

/**
 * @returns {Promise<{usesCount:number,title:string|null,artist:string|null,coverImageUrl:string|null}|null>}
 */
export async function fetchSoundStatsViaBrowser(tiktokSoundId, { timeoutMs = 60_000 } = {}) {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ userAgent: UA, viewport: { width: 1400, height: 1000 } });

    // Take the JSON the page fetches for itself rather than scraping the DOM:
    // same numbers, plus the title, artist and cover art, and no dependence on
    // how TikTok happens to word "46 videos" this month.
    let payload = null;
    page.on("response", async (res) => {
      if (payload || !res.url().includes("/api/music/detail/")) return;
      try {
        const body = await res.text();
        if (body) payload = JSON.parse(body);
      } catch {
        /* a truncated or non-JSON body is just not the answer; keep waiting */
      }
    });

    await page.goto(`https://www.tiktok.com/music/x-${encodeURIComponent(tiktokSoundId)}`, {
      waitUntil: "domcontentloaded",
      timeout: timeoutMs,
    });

    const deadline = Date.now() + 25_000;
    while (!payload && Date.now() < deadline) await page.waitForTimeout(500);
    if (!payload) return null;

    const info = payload.musicInfo ?? payload.music_info;
    const music = info?.music ?? info;
    const uses = info?.stats?.videoCount ?? music?.videoCount;
    if (typeof uses !== "number" || !Number.isFinite(uses)) return null;

    return {
      usesCount: uses,
      title: typeof music?.title === "string" && music.title ? music.title : null,
      artist: typeof music?.authorName === "string" && music.authorName ? music.authorName : null,
      coverImageUrl: music?.coverLarge ?? music?.coverMedium ?? music?.coverThumb ?? null,
    };
  } finally {
    await browser.close();
  }
}
